### ISSUE TITLE
Keyboard shifts Window

### ISSUE THREAD

**Issue by Biolla** [jlempen/gnome-shell-osk-tweaks#1]
Very nice extension, which allows me to use Gnome on a small touch screen for a media center.
Only problem: Every time i start the on screen keyboard it shifts the active window up.
Because of the small touchscreen this is a little bit annyoing. 
Adding an option to enable or disable the shifting function would make the extension perfect!

**Comment by jlempen** [comment]
Hey Biolla,

Thanks for the nice words!

I'm afraid I won't update this extension anymore. For one, I don't use the GNOME desktop anymore. Although I really do like GNOME, I need to install way too many extensions to make it work the way I like it. And of course half of these extensions break on every major update of the GNOME desktop. And the same goes for the extension developers. For instance, adapting this extension to GNOME 3.36 has taken me way too many working hours because more than half of the code had to be rewritten entirely. I'll see if I can find that code (for GNOME Shell 3.36) again and update this repository with it.

As it was designed by the developers, the GNOME shell OSK keyboard works nicely on larger tablets such as the Surface Pro 12.3" tablets, but the keys are way too small on smaller tablets such as the 10.1" Surface Go or 10.5" Surface Go 2 tablets. That's why I've written this extension. Changing the global size of the OSK is actually very easy, but changing the aspect ratio of the keys is not. And making the keyboard larger without making the keys wider takes way too much screen estate on smaller tablets. As the developers are not very open to allowing the user to change the aspect ratio of the OSK's keys, I don't want to fight against the wind and have the extension break every six months.

But of course feel free to fork this repo and make your own extension. My code is quite well documented, by the way :-)

To fix your issue with the active window shifting up (which was supposed to be a "feature"...), please open the file "extension.js" in the extension's folder and comment out or remove the following two lines:

On line 124:
`Main.layoutManager.removeChrome(Main.layoutManager.keyboardBox);
`
On line 151:
`Main.layoutManager.addChrome(Main.layoutManager.keyboardBox, { affectsStruts: true, trackFullscreen: false });`

Thanks again for your kind words and cheers!

Jürg
